default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: delivery_app_development
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: 127.0.0.1

test:
  <<: *default
  database: delivery_app_test
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: 127.0.0.1

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
